/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Absensi {
  'status' : StatusAbsensi,
  'dicatatOleh' : [] | [Principal],
  'sesiId' : SesiId,
  'waktuCatat' : Timestamp,
  'pesertaId' : PesertaId,
  'catatan' : string,
}
export interface AbsensiInput {
  'status' : StatusAbsensi,
  'pesertaId' : PesertaId,
  'catatan' : string,
}
export interface AmbangInput { 'persentase' : number }
export interface Cell { 'value' : Value, 'name' : string }
export interface CheckInInput { 'token' : string, 'pesertaId' : PesertaId }
export interface DashboardRingkasan {
  'halaqahTerendah' : [] | [RekapKelompok],
  'kehadiranBulanIni' : number,
  'sesiTerdekat' : [] | [SesiRingkas],
}
export interface DuplikatInput {
  'sesiId' : SesiId,
  'tanggalTujuan' : Array<Timestamp>,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type KelompokId = string;
export type MapelId = bigint;
export interface MataPelajaran { 'id' : MapelId, 'nama' : string }
export interface MataPelajaranInput { 'nama' : string }
export type MediaSesi = { 'zoom' : null } |
  { 'whatsapp' : null } |
  { 'tatapMuka' : null };
export interface Peserta {
  'id' : PesertaId,
  'kelompokId' : KelompokId,
  'nama' : string,
}
export interface PesertaAbsensiView {
  'status' : StatusAbsensi,
  'nama' : string,
  'pesertaId' : PesertaId,
  'catatan' : string,
}
export interface PesertaFilter {
  'kelompokId' : [] | [KelompokId],
  'nama' : [] | [string],
}
export type PesertaId = bigint;
export interface PesertaInput { 'kelompokId' : KelompokId, 'nama' : string }
export interface RekapBulanan {
  'tahun' : bigint,
  'totalHadir' : bigint,
  'totalSesi' : bigint,
  'persentase' : number,
  'bulan' : bigint,
}
export interface RekapFilter {
  'tahun' : [] | [bigint],
  'kelompokId' : [] | [KelompokId],
  'bulan' : [] | [bigint],
}
export interface RekapKelompok {
  'kelompokId' : KelompokId,
  'totalHadir' : bigint,
  'nama' : string,
  'totalSesi' : bigint,
  'persentase' : number,
}
export interface RekapPeserta {
  'kelompokId' : KelompokId,
  'hadir' : bigint,
  'nama' : string,
  'totalSesi' : bigint,
  'persentase' : number,
  'pesertaId' : PesertaId,
  'diBawahAmbang' : boolean,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface RingkasanStatus {
  'total' : bigint,
  'hadir' : bigint,
  'alpa' : bigint,
  'izin' : bigint,
  'sakit' : bigint,
}
export interface Sesi {
  'id' : SesiId,
  'media' : MediaSesi,
  'kelompokId' : KelompokId,
  'pemateri' : string,
  'tanggal' : Timestamp,
  'mapelId' : MapelId,
  'jendelaSelesai' : Timestamp,
  'checkInToken' : [] | [string],
  'jendelaMulai' : Timestamp,
  'tempat' : [] | [string],
}
export interface SesiDetail {
  'peserta' : Array<PesertaAbsensiView>,
  'sesi' : Sesi,
}
export interface SesiFilter {
  'tahun' : [] | [bigint],
  'kelompokId' : [] | [KelompokId],
  'mapelId' : [] | [MapelId],
  'bulan' : [] | [bigint],
}
export type SesiId = bigint;
export interface SesiInput {
  'media' : MediaSesi,
  'kelompokId' : KelompokId,
  'pemateri' : string,
  'tanggal' : Timestamp,
  'mapelId' : MapelId,
  'jendelaSelesai' : Timestamp,
  'jendelaMulai' : Timestamp,
  'tempat' : [] | [string],
}
export interface SesiRingkas {
  'id' : SesiId,
  'media' : MediaSesi,
  'kelompokId' : KelompokId,
  'pemateri' : string,
  'tanggal' : Timestamp,
  'mapelId' : MapelId,
}
export interface SimpanAbsensiInput {
  'daftar' : Array<AbsensiInput>,
  'sesiId' : SesiId,
}
export type StatusAbsensi = { 'hadir' : null } |
  { 'alpa' : null } |
  { 'izin' : null } |
  { 'sakit' : null };
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'buatSesi' : ActorMethod<[SesiInput], Sesi>,
  'checkIn' : ActorMethod<[CheckInInput], Absensi>,
  'daftarkanAnggota' : ActorMethod<[Principal, PesertaId], undefined>,
  'daftarkanKetuaHalaqah' : ActorMethod<[Principal, KelompokId], undefined>,
  'dashboard' : ActorMethod<[], DashboardRingkasan>,
  'detailSesi' : ActorMethod<[SesiId], [] | [SesiDetail]>,
  'duplikatSesi' : ActorMethod<[DuplikatInput], Array<Sesi>>,
  'eksporRekapExcel' : ActorMethod<[RekapFilter], Uint8Array>,
  'eksporRekapPdf' : ActorMethod<[RekapFilter], Uint8Array>,
  'execute' : ActorMethod<[string], Result>,
  'getAbsensiSesi' : ActorMethod<[SesiId], Array<Absensi>>,
  'getAmbang' : ActorMethod<[], number>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getKelompokSaya' : ActorMethod<[], Array<KelompokId>>,
  'getPeserta' : ActorMethod<[PesertaId], [] | [Peserta]>,
  'getPesertaSaya' : ActorMethod<[], [] | [PesertaId]>,
  'getSesi' : ActorMethod<[SesiId], [] | [Sesi]>,
  'hapusAnggota' : ActorMethod<[Principal], undefined>,
  'hapusKetuaHalaqah' : ActorMethod<[Principal], undefined>,
  'hapusMapel' : ActorMethod<[MapelId], boolean>,
  'hapusPeserta' : ActorMethod<[PesertaId], boolean>,
  'hapusSesi' : ActorMethod<[SesiId], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMapel' : ActorMethod<[], Array<MataPelajaran>>,
  'listPeserta' : ActorMethod<[PesertaFilter], Array<Peserta>>,
  'listSesi' : ActorMethod<[SesiFilter], Array<Sesi>>,
  'rekapBulanan' : ActorMethod<[bigint, bigint], RekapBulanan>,
  'rekapPerKelompok' : ActorMethod<[RekapFilter], Array<RekapKelompok>>,
  'rekapPerPeserta' : ActorMethod<[RekapFilter], Array<RekapPeserta>>,
  'ringkasanSesi' : ActorMethod<[SesiId], RingkasanStatus>,
  'schema' : ActorMethod<[], string>,
  'setAmbang' : ActorMethod<[AmbangInput], number>,
  'simpanAbsensi' : ActorMethod<[SimpanAbsensiInput], RingkasanStatus>,
  'tambahMapel' : ActorMethod<[MataPelajaranInput], MataPelajaran>,
  'tambahPeserta' : ActorMethod<[PesertaInput], Peserta>,
  'ubahMapel' : ActorMethod<
    [MapelId, MataPelajaranInput],
    [] | [MataPelajaran]
  >,
  'ubahPeserta' : ActorMethod<[PesertaId, PesertaInput], [] | [Peserta]>,
  'ubahSesi' : ActorMethod<[SesiId, SesiInput], [] | [Sesi]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];