/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MediaSesi = IDL.Variant({
  'zoom' : IDL.Null,
  'whatsapp' : IDL.Null,
  'tatapMuka' : IDL.Null,
});
export const KelompokId = IDL.Text;
export const Timestamp = IDL.Int;
export const MapelId = IDL.Nat;
export const SesiInput = IDL.Record({
  'media' : MediaSesi,
  'kelompokId' : KelompokId,
  'pemateri' : IDL.Text,
  'tanggal' : Timestamp,
  'mapelId' : MapelId,
  'jendelaSelesai' : Timestamp,
  'jendelaMulai' : Timestamp,
  'tempat' : IDL.Opt(IDL.Text),
});
export const SesiId = IDL.Nat;
export const Sesi = IDL.Record({
  'id' : SesiId,
  'media' : MediaSesi,
  'kelompokId' : KelompokId,
  'pemateri' : IDL.Text,
  'tanggal' : Timestamp,
  'mapelId' : MapelId,
  'jendelaSelesai' : Timestamp,
  'checkInToken' : IDL.Opt(IDL.Text),
  'jendelaMulai' : Timestamp,
  'tempat' : IDL.Opt(IDL.Text),
});
export const PesertaId = IDL.Nat;
export const CheckInInput = IDL.Record({
  'token' : IDL.Text,
  'pesertaId' : PesertaId,
});
export const StatusAbsensi = IDL.Variant({
  'hadir' : IDL.Null,
  'alpa' : IDL.Null,
  'izin' : IDL.Null,
  'sakit' : IDL.Null,
});
export const Absensi = IDL.Record({
  'status' : StatusAbsensi,
  'dicatatOleh' : IDL.Opt(IDL.Principal),
  'sesiId' : SesiId,
  'waktuCatat' : Timestamp,
  'pesertaId' : PesertaId,
  'catatan' : IDL.Text,
});
export const RekapKelompok = IDL.Record({
  'kelompokId' : KelompokId,
  'totalHadir' : IDL.Nat,
  'nama' : IDL.Text,
  'totalSesi' : IDL.Nat,
  'persentase' : IDL.Float64,
});
export const SesiRingkas = IDL.Record({
  'id' : SesiId,
  'media' : MediaSesi,
  'kelompokId' : KelompokId,
  'pemateri' : IDL.Text,
  'tanggal' : Timestamp,
  'mapelId' : MapelId,
});
export const DashboardRingkasan = IDL.Record({
  'halaqahTerendah' : IDL.Opt(RekapKelompok),
  'kehadiranBulanIni' : IDL.Float64,
  'sesiTerdekat' : IDL.Opt(SesiRingkas),
});
export const PesertaAbsensiView = IDL.Record({
  'status' : StatusAbsensi,
  'nama' : IDL.Text,
  'pesertaId' : PesertaId,
  'catatan' : IDL.Text,
});
export const SesiDetail = IDL.Record({
  'peserta' : IDL.Vec(PesertaAbsensiView),
  'sesi' : Sesi,
});
export const DuplikatInput = IDL.Record({
  'sesiId' : SesiId,
  'tanggalTujuan' : IDL.Vec(Timestamp),
});
export const RekapFilter = IDL.Record({
  'tahun' : IDL.Opt(IDL.Nat),
  'kelompokId' : IDL.Opt(KelompokId),
  'bulan' : IDL.Opt(IDL.Nat),
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Peserta = IDL.Record({
  'id' : PesertaId,
  'kelompokId' : KelompokId,
  'nama' : IDL.Text,
});
export const MataPelajaran = IDL.Record({ 'id' : MapelId, 'nama' : IDL.Text });
export const PesertaFilter = IDL.Record({
  'kelompokId' : IDL.Opt(KelompokId),
  'nama' : IDL.Opt(IDL.Text),
});
export const SesiFilter = IDL.Record({
  'tahun' : IDL.Opt(IDL.Nat),
  'kelompokId' : IDL.Opt(KelompokId),
  'mapelId' : IDL.Opt(MapelId),
  'bulan' : IDL.Opt(IDL.Nat),
});
export const RekapBulanan = IDL.Record({
  'tahun' : IDL.Nat,
  'totalHadir' : IDL.Nat,
  'totalSesi' : IDL.Nat,
  'persentase' : IDL.Float64,
  'bulan' : IDL.Nat,
});
export const RekapPeserta = IDL.Record({
  'kelompokId' : KelompokId,
  'hadir' : IDL.Nat,
  'nama' : IDL.Text,
  'totalSesi' : IDL.Nat,
  'persentase' : IDL.Float64,
  'pesertaId' : PesertaId,
  'diBawahAmbang' : IDL.Bool,
});
export const RingkasanStatus = IDL.Record({
  'total' : IDL.Nat,
  'hadir' : IDL.Nat,
  'alpa' : IDL.Nat,
  'izin' : IDL.Nat,
  'sakit' : IDL.Nat,
});
export const AmbangInput = IDL.Record({ 'persentase' : IDL.Float64 });
export const AbsensiInput = IDL.Record({
  'status' : StatusAbsensi,
  'pesertaId' : PesertaId,
  'catatan' : IDL.Text,
});
export const SimpanAbsensiInput = IDL.Record({
  'daftar' : IDL.Vec(AbsensiInput),
  'sesiId' : SesiId,
});
export const MataPelajaranInput = IDL.Record({ 'nama' : IDL.Text });
export const PesertaInput = IDL.Record({
  'kelompokId' : KelompokId,
  'nama' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'buatSesi' : IDL.Func([SesiInput], [Sesi], []),
  'checkIn' : IDL.Func([CheckInInput], [Absensi], []),
  'daftarkanAnggota' : IDL.Func([IDL.Principal, PesertaId], [], []),
  'daftarkanKetuaHalaqah' : IDL.Func([IDL.Principal, KelompokId], [], []),
  'dashboard' : IDL.Func([], [DashboardRingkasan], ['query']),
  'detailSesi' : IDL.Func([SesiId], [IDL.Opt(SesiDetail)], ['query']),
  'duplikatSesi' : IDL.Func([DuplikatInput], [IDL.Vec(Sesi)], []),
  'eksporRekapExcel' : IDL.Func([RekapFilter], [IDL.Vec(IDL.Nat8)], ['query']),
  'eksporRekapPdf' : IDL.Func([RekapFilter], [IDL.Vec(IDL.Nat8)], ['query']),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getAbsensiSesi' : IDL.Func([SesiId], [IDL.Vec(Absensi)], ['query']),
  'getAmbang' : IDL.Func([], [IDL.Float64], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getKelompokSaya' : IDL.Func([], [IDL.Vec(KelompokId)], ['query']),
  'getPeserta' : IDL.Func([PesertaId], [IDL.Opt(Peserta)], ['query']),
  'getPesertaSaya' : IDL.Func([], [IDL.Opt(PesertaId)], ['query']),
  'getSesi' : IDL.Func([SesiId], [IDL.Opt(Sesi)], ['query']),
  'hapusAnggota' : IDL.Func([IDL.Principal], [], []),
  'hapusKetuaHalaqah' : IDL.Func([IDL.Principal], [], []),
  'hapusMapel' : IDL.Func([MapelId], [IDL.Bool], []),
  'hapusPeserta' : IDL.Func([PesertaId], [IDL.Bool], []),
  'hapusSesi' : IDL.Func([SesiId], [IDL.Bool], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMapel' : IDL.Func([], [IDL.Vec(MataPelajaran)], ['query']),
  'listPeserta' : IDL.Func([PesertaFilter], [IDL.Vec(Peserta)], ['query']),
  'listSesi' : IDL.Func([SesiFilter], [IDL.Vec(Sesi)], ['query']),
  'rekapBulanan' : IDL.Func([IDL.Nat, IDL.Nat], [RekapBulanan], ['query']),
  'rekapPerKelompok' : IDL.Func(
      [RekapFilter],
      [IDL.Vec(RekapKelompok)],
      ['query'],
    ),
  'rekapPerPeserta' : IDL.Func(
      [RekapFilter],
      [IDL.Vec(RekapPeserta)],
      ['query'],
    ),
  'ringkasanSesi' : IDL.Func([SesiId], [RingkasanStatus], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setAmbang' : IDL.Func([AmbangInput], [IDL.Float64], []),
  'simpanAbsensi' : IDL.Func([SimpanAbsensiInput], [RingkasanStatus], []),
  'tambahMapel' : IDL.Func([MataPelajaranInput], [MataPelajaran], []),
  'tambahPeserta' : IDL.Func([PesertaInput], [Peserta], []),
  'ubahMapel' : IDL.Func(
      [MapelId, MataPelajaranInput],
      [IDL.Opt(MataPelajaran)],
      [],
    ),
  'ubahPeserta' : IDL.Func([PesertaId, PesertaInput], [IDL.Opt(Peserta)], []),
  'ubahSesi' : IDL.Func([SesiId, SesiInput], [IDL.Opt(Sesi)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MediaSesi = IDL.Variant({
    'zoom' : IDL.Null,
    'whatsapp' : IDL.Null,
    'tatapMuka' : IDL.Null,
  });
  const KelompokId = IDL.Text;
  const Timestamp = IDL.Int;
  const MapelId = IDL.Nat;
  const SesiInput = IDL.Record({
    'media' : MediaSesi,
    'kelompokId' : KelompokId,
    'pemateri' : IDL.Text,
    'tanggal' : Timestamp,
    'mapelId' : MapelId,
    'jendelaSelesai' : Timestamp,
    'jendelaMulai' : Timestamp,
    'tempat' : IDL.Opt(IDL.Text),
  });
  const SesiId = IDL.Nat;
  const Sesi = IDL.Record({
    'id' : SesiId,
    'media' : MediaSesi,
    'kelompokId' : KelompokId,
    'pemateri' : IDL.Text,
    'tanggal' : Timestamp,
    'mapelId' : MapelId,
    'jendelaSelesai' : Timestamp,
    'checkInToken' : IDL.Opt(IDL.Text),
    'jendelaMulai' : Timestamp,
    'tempat' : IDL.Opt(IDL.Text),
  });
  const PesertaId = IDL.Nat;
  const CheckInInput = IDL.Record({
    'token' : IDL.Text,
    'pesertaId' : PesertaId,
  });
  const StatusAbsensi = IDL.Variant({
    'hadir' : IDL.Null,
    'alpa' : IDL.Null,
    'izin' : IDL.Null,
    'sakit' : IDL.Null,
  });
  const Absensi = IDL.Record({
    'status' : StatusAbsensi,
    'dicatatOleh' : IDL.Opt(IDL.Principal),
    'sesiId' : SesiId,
    'waktuCatat' : Timestamp,
    'pesertaId' : PesertaId,
    'catatan' : IDL.Text,
  });
  const RekapKelompok = IDL.Record({
    'kelompokId' : KelompokId,
    'totalHadir' : IDL.Nat,
    'nama' : IDL.Text,
    'totalSesi' : IDL.Nat,
    'persentase' : IDL.Float64,
  });
  const SesiRingkas = IDL.Record({
    'id' : SesiId,
    'media' : MediaSesi,
    'kelompokId' : KelompokId,
    'pemateri' : IDL.Text,
    'tanggal' : Timestamp,
    'mapelId' : MapelId,
  });
  const DashboardRingkasan = IDL.Record({
    'halaqahTerendah' : IDL.Opt(RekapKelompok),
    'kehadiranBulanIni' : IDL.Float64,
    'sesiTerdekat' : IDL.Opt(SesiRingkas),
  });
  const PesertaAbsensiView = IDL.Record({
    'status' : StatusAbsensi,
    'nama' : IDL.Text,
    'pesertaId' : PesertaId,
    'catatan' : IDL.Text,
  });
  const SesiDetail = IDL.Record({
    'peserta' : IDL.Vec(PesertaAbsensiView),
    'sesi' : Sesi,
  });
  const DuplikatInput = IDL.Record({
    'sesiId' : SesiId,
    'tanggalTujuan' : IDL.Vec(Timestamp),
  });
  const RekapFilter = IDL.Record({
    'tahun' : IDL.Opt(IDL.Nat),
    'kelompokId' : IDL.Opt(KelompokId),
    'bulan' : IDL.Opt(IDL.Nat),
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Peserta = IDL.Record({
    'id' : PesertaId,
    'kelompokId' : KelompokId,
    'nama' : IDL.Text,
  });
  const MataPelajaran = IDL.Record({ 'id' : MapelId, 'nama' : IDL.Text });
  const PesertaFilter = IDL.Record({
    'kelompokId' : IDL.Opt(KelompokId),
    'nama' : IDL.Opt(IDL.Text),
  });
  const SesiFilter = IDL.Record({
    'tahun' : IDL.Opt(IDL.Nat),
    'kelompokId' : IDL.Opt(KelompokId),
    'mapelId' : IDL.Opt(MapelId),
    'bulan' : IDL.Opt(IDL.Nat),
  });
  const RekapBulanan = IDL.Record({
    'tahun' : IDL.Nat,
    'totalHadir' : IDL.Nat,
    'totalSesi' : IDL.Nat,
    'persentase' : IDL.Float64,
    'bulan' : IDL.Nat,
  });
  const RekapPeserta = IDL.Record({
    'kelompokId' : KelompokId,
    'hadir' : IDL.Nat,
    'nama' : IDL.Text,
    'totalSesi' : IDL.Nat,
    'persentase' : IDL.Float64,
    'pesertaId' : PesertaId,
    'diBawahAmbang' : IDL.Bool,
  });
  const RingkasanStatus = IDL.Record({
    'total' : IDL.Nat,
    'hadir' : IDL.Nat,
    'alpa' : IDL.Nat,
    'izin' : IDL.Nat,
    'sakit' : IDL.Nat,
  });
  const AmbangInput = IDL.Record({ 'persentase' : IDL.Float64 });
  const AbsensiInput = IDL.Record({
    'status' : StatusAbsensi,
    'pesertaId' : PesertaId,
    'catatan' : IDL.Text,
  });
  const SimpanAbsensiInput = IDL.Record({
    'daftar' : IDL.Vec(AbsensiInput),
    'sesiId' : SesiId,
  });
  const MataPelajaranInput = IDL.Record({ 'nama' : IDL.Text });
  const PesertaInput = IDL.Record({
    'kelompokId' : KelompokId,
    'nama' : IDL.Text,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'buatSesi' : IDL.Func([SesiInput], [Sesi], []),
    'checkIn' : IDL.Func([CheckInInput], [Absensi], []),
    'daftarkanAnggota' : IDL.Func([IDL.Principal, PesertaId], [], []),
    'daftarkanKetuaHalaqah' : IDL.Func([IDL.Principal, KelompokId], [], []),
    'dashboard' : IDL.Func([], [DashboardRingkasan], ['query']),
    'detailSesi' : IDL.Func([SesiId], [IDL.Opt(SesiDetail)], ['query']),
    'duplikatSesi' : IDL.Func([DuplikatInput], [IDL.Vec(Sesi)], []),
    'eksporRekapExcel' : IDL.Func(
        [RekapFilter],
        [IDL.Vec(IDL.Nat8)],
        ['query'],
      ),
    'eksporRekapPdf' : IDL.Func([RekapFilter], [IDL.Vec(IDL.Nat8)], ['query']),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getAbsensiSesi' : IDL.Func([SesiId], [IDL.Vec(Absensi)], ['query']),
    'getAmbang' : IDL.Func([], [IDL.Float64], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getKelompokSaya' : IDL.Func([], [IDL.Vec(KelompokId)], ['query']),
    'getPeserta' : IDL.Func([PesertaId], [IDL.Opt(Peserta)], ['query']),
    'getPesertaSaya' : IDL.Func([], [IDL.Opt(PesertaId)], ['query']),
    'getSesi' : IDL.Func([SesiId], [IDL.Opt(Sesi)], ['query']),
    'hapusAnggota' : IDL.Func([IDL.Principal], [], []),
    'hapusKetuaHalaqah' : IDL.Func([IDL.Principal], [], []),
    'hapusMapel' : IDL.Func([MapelId], [IDL.Bool], []),
    'hapusPeserta' : IDL.Func([PesertaId], [IDL.Bool], []),
    'hapusSesi' : IDL.Func([SesiId], [IDL.Bool], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMapel' : IDL.Func([], [IDL.Vec(MataPelajaran)], ['query']),
    'listPeserta' : IDL.Func([PesertaFilter], [IDL.Vec(Peserta)], ['query']),
    'listSesi' : IDL.Func([SesiFilter], [IDL.Vec(Sesi)], ['query']),
    'rekapBulanan' : IDL.Func([IDL.Nat, IDL.Nat], [RekapBulanan], ['query']),
    'rekapPerKelompok' : IDL.Func(
        [RekapFilter],
        [IDL.Vec(RekapKelompok)],
        ['query'],
      ),
    'rekapPerPeserta' : IDL.Func(
        [RekapFilter],
        [IDL.Vec(RekapPeserta)],
        ['query'],
      ),
    'ringkasanSesi' : IDL.Func([SesiId], [RingkasanStatus], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setAmbang' : IDL.Func([AmbangInput], [IDL.Float64], []),
    'simpanAbsensi' : IDL.Func([SimpanAbsensiInput], [RingkasanStatus], []),
    'tambahMapel' : IDL.Func([MataPelajaranInput], [MataPelajaran], []),
    'tambahPeserta' : IDL.Func([PesertaInput], [Peserta], []),
    'ubahMapel' : IDL.Func(
        [MapelId, MataPelajaranInput],
        [IDL.Opt(MataPelajaran)],
        [],
      ),
    'ubahPeserta' : IDL.Func([PesertaId, PesertaInput], [IDL.Opt(Peserta)], []),
    'ubahSesi' : IDL.Func([SesiId, SesiInput], [IDL.Opt(Sesi)], []),
  });
};

export const init = ({ IDL }) => { return []; };