/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Absensi {
    status: StatusAbsensi;
    dicatatOleh?: Principal;
    sesiId: SesiId;
    waktuCatat: Timestamp;
    pesertaId: PesertaId;
    catatan: string;
}
export interface AbsensiInput {
    status: StatusAbsensi;
    pesertaId: PesertaId;
    catatan: string;
}
export interface AmbangInput {
    persentase: number;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface CheckInInput {
    token: string;
    pesertaId: PesertaId;
}
export interface DashboardRingkasan {
    halaqahTerendah?: RekapKelompok;
    kehadiranBulanIni: number;
    sesiTerdekat?: SesiRingkas;
}
export interface DuplikatInput {
    sesiId: SesiId;
    tanggalTujuan: Array<Timestamp>;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export type KelompokId = string;
export type MapelId = bigint;
export interface MataPelajaran {
    id: MapelId;
    nama: string;
}
export interface MataPelajaranInput {
    nama: string;
}
export interface Peserta {
    id: PesertaId;
    kelompokId: KelompokId;
    nama: string;
}
export interface PesertaAbsensiView {
    status: StatusAbsensi;
    nama: string;
    pesertaId: PesertaId;
    catatan: string;
}
export interface PesertaFilter {
    kelompokId?: KelompokId;
    nama?: string;
}
export type PesertaId = bigint;
export interface PesertaInput {
    kelompokId: KelompokId;
    nama: string;
}
export interface RekapBulanan {
    tahun: bigint;
    totalHadir: bigint;
    totalSesi: bigint;
    persentase: number;
    bulan: bigint;
}
export interface RekapFilter {
    tahun?: bigint;
    kelompokId?: KelompokId;
    bulan?: bigint;
}
export interface RekapKelompok {
    kelompokId: KelompokId;
    totalHadir: bigint;
    nama: string;
    totalSesi: bigint;
    persentase: number;
}
export interface RekapPeserta {
    kelompokId: KelompokId;
    hadir: bigint;
    nama: string;
    totalSesi: bigint;
    persentase: number;
    pesertaId: PesertaId;
    diBawahAmbang: boolean;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface RingkasanStatus {
    total: bigint;
    hadir: bigint;
    alpa: bigint;
    izin: bigint;
    sakit: bigint;
}
export interface Sesi {
    id: SesiId;
    media: MediaSesi;
    kelompokId: KelompokId;
    pemateri: string;
    tanggal: Timestamp;
    mapelId: MapelId;
    jendelaSelesai: Timestamp;
    checkInToken?: string;
    jendelaMulai: Timestamp;
    tempat?: string;
}
export interface SesiDetail {
    peserta: Array<PesertaAbsensiView>;
    sesi: Sesi;
}
export interface SesiFilter {
    tahun?: bigint;
    kelompokId?: KelompokId;
    mapelId?: MapelId;
    bulan?: bigint;
}
export type SesiId = bigint;
export interface SesiInput {
    media: MediaSesi;
    kelompokId: KelompokId;
    pemateri: string;
    tanggal: Timestamp;
    mapelId: MapelId;
    jendelaSelesai: Timestamp;
    jendelaMulai: Timestamp;
    tempat?: string;
}
export interface SesiRingkas {
    id: SesiId;
    media: MediaSesi;
    kelompokId: KelompokId;
    pemateri: string;
    tanggal: Timestamp;
    mapelId: MapelId;
}
export interface SimpanAbsensiInput {
    daftar: Array<AbsensiInput>;
    sesiId: SesiId;
}
export type Timestamp = bigint;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum MediaSesi {
    zoom = "zoom",
    whatsapp = "whatsapp",
    tatapMuka = "tatapMuka"
}
export enum StatusAbsensi {
    hadir = "hadir",
    alpa = "alpa",
    izin = "izin",
    sakit = "sakit"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    buatSesi(input: SesiInput): Promise<Sesi>;
    checkIn(input: CheckInInput): Promise<Absensi>;
    daftarkanAnggota(principal: Principal, pesertaId: PesertaId): Promise<void>;
    daftarkanKetuaHalaqah(principal: Principal, kelompokId: KelompokId): Promise<void>;
    dashboard(): Promise<DashboardRingkasan>;
    detailSesi(id: SesiId): Promise<SesiDetail | null>;
    duplikatSesi(input: DuplikatInput): Promise<Array<Sesi>>;
    eksporRekapExcel(filter: RekapFilter): Promise<Uint8Array>;
    eksporRekapPdf(filter: RekapFilter): Promise<Uint8Array>;
    execute(qJson: string): Promise<Result>;
    getAbsensiSesi(sesiId: SesiId): Promise<Array<Absensi>>;
    getAmbang(): Promise<number>;
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    getKelompokSaya(): Promise<Array<KelompokId>>;
    getPeserta(id: PesertaId): Promise<Peserta | null>;
    getPesertaSaya(): Promise<PesertaId | null>;
    getSesi(id: SesiId): Promise<Sesi | null>;
    hapusAnggota(principal: Principal): Promise<void>;
    hapusKetuaHalaqah(principal: Principal): Promise<void>;
    hapusMapel(id: MapelId): Promise<boolean>;
    hapusPeserta(id: PesertaId): Promise<boolean>;
    hapusSesi(id: SesiId): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    listMapel(): Promise<Array<MataPelajaran>>;
    listPeserta(filter: PesertaFilter): Promise<Array<Peserta>>;
    listSesi(filter: SesiFilter): Promise<Array<Sesi>>;
    rekapBulanan(bulan: bigint, tahun: bigint): Promise<RekapBulanan>;
    rekapPerKelompok(filter: RekapFilter): Promise<Array<RekapKelompok>>;
    rekapPerPeserta(filter: RekapFilter): Promise<Array<RekapPeserta>>;
    ringkasanSesi(sesiId: SesiId): Promise<RingkasanStatus>;
    schema(): Promise<string>;
    setAmbang(input: AmbangInput): Promise<number>;
    simpanAbsensi(input: SimpanAbsensiInput): Promise<RingkasanStatus>;
    tambahMapel(input: MataPelajaranInput): Promise<MataPelajaran>;
    tambahPeserta(input: PesertaInput): Promise<Peserta>;
    ubahMapel(id: MapelId, input: MataPelajaranInput): Promise<MataPelajaran | null>;
    ubahPeserta(id: PesertaId, input: PesertaInput): Promise<Peserta | null>;
    ubahSesi(id: SesiId, input: SesiInput): Promise<Sesi | null>;
}
import type { Absensi as _Absensi, AbsensiInput as _AbsensiInput, Cell as _Cell, DashboardRingkasan as _DashboardRingkasan, Error as _Error, KelompokId as _KelompokId, MapelId as _MapelId, MataPelajaran as _MataPelajaran, MediaSesi as _MediaSesi, Peserta as _Peserta, PesertaAbsensiView as _PesertaAbsensiView, PesertaFilter as _PesertaFilter, PesertaId as _PesertaId, RekapFilter as _RekapFilter, RekapKelompok as _RekapKelompok, Result as _Result, Result__1 as _Result__1, Sesi as _Sesi, SesiDetail as _SesiDetail, SesiFilter as _SesiFilter, SesiId as _SesiId, SesiInput as _SesiInput, SesiRingkas as _SesiRingkas, SimpanAbsensiInput as _SimpanAbsensiInput, StatusAbsensi as _StatusAbsensi, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async buatSesi(arg0: SesiInput): Promise<Sesi> {
        if (this.processError) {
            try {
                const result = await this.actor.buatSesi(to_candid_SesiInput_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Sesi_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.buatSesi(to_candid_SesiInput_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Sesi_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkIn(arg0: CheckInInput): Promise<Absensi> {
        if (this.processError) {
            try {
                const result = await this.actor.checkIn(arg0);
                return from_candid_Absensi_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkIn(arg0);
            return from_candid_Absensi_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async daftarkanAnggota(arg0: Principal, arg1: PesertaId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.daftarkanAnggota(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.daftarkanAnggota(arg0, arg1);
            return result;
        }
    }
    async daftarkanKetuaHalaqah(arg0: Principal, arg1: KelompokId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.daftarkanKetuaHalaqah(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.daftarkanKetuaHalaqah(arg0, arg1);
            return result;
        }
    }
    async dashboard(): Promise<DashboardRingkasan> {
        if (this.processError) {
            try {
                const result = await this.actor.dashboard();
                return from_candid_DashboardRingkasan_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dashboard();
            return from_candid_DashboardRingkasan_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async detailSesi(arg0: SesiId): Promise<SesiDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.detailSesi(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.detailSesi(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async duplikatSesi(arg0: DuplikatInput): Promise<Array<Sesi>> {
        if (this.processError) {
            try {
                const result = await this.actor.duplikatSesi(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duplikatSesi(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async eksporRekapExcel(arg0: RekapFilter): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor.eksporRekapExcel(to_candid_RekapFilter_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.eksporRekapExcel(to_candid_RekapFilter_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async eksporRekapPdf(arg0: RekapFilter): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor.eksporRekapPdf(to_candid_RekapFilter_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.eksporRekapPdf(to_candid_RekapFilter_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAbsensiSesi(arg0: SesiId): Promise<Array<Absensi>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAbsensiSesi(arg0);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAbsensiSesi(arg0);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAmbang(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getAmbang();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAmbang();
            return result;
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKelompokSaya(): Promise<Array<KelompokId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getKelompokSaya();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKelompokSaya();
            return result;
        }
    }
    async getPeserta(arg0: PesertaId): Promise<Peserta | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPeserta(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPeserta(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPesertaSaya(): Promise<PesertaId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPesertaSaya();
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPesertaSaya();
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSesi(arg0: SesiId): Promise<Sesi | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSesi(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSesi(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async hapusAnggota(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.hapusAnggota(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hapusAnggota(arg0);
            return result;
        }
    }
    async hapusKetuaHalaqah(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.hapusKetuaHalaqah(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hapusKetuaHalaqah(arg0);
            return result;
        }
    }
    async hapusMapel(arg0: MapelId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hapusMapel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hapusMapel(arg0);
            return result;
        }
    }
    async hapusPeserta(arg0: PesertaId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hapusPeserta(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hapusPeserta(arg0);
            return result;
        }
    }
    async hapusSesi(arg0: SesiId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hapusSesi(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hapusSesi(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listMapel(): Promise<Array<MataPelajaran>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMapel();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMapel();
            return result;
        }
    }
    async listPeserta(arg0: PesertaFilter): Promise<Array<Peserta>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPeserta(to_candid_PesertaFilter_n45(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPeserta(to_candid_PesertaFilter_n45(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async listSesi(arg0: SesiFilter): Promise<Array<Sesi>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSesi(to_candid_SesiFilter_n47(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSesi(to_candid_SesiFilter_n47(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async rekapBulanan(arg0: bigint, arg1: bigint): Promise<RekapBulanan> {
        if (this.processError) {
            try {
                const result = await this.actor.rekapBulanan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rekapBulanan(arg0, arg1);
            return result;
        }
    }
    async rekapPerKelompok(arg0: RekapFilter): Promise<Array<RekapKelompok>> {
        if (this.processError) {
            try {
                const result = await this.actor.rekapPerKelompok(to_candid_RekapFilter_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rekapPerKelompok(to_candid_RekapFilter_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async rekapPerPeserta(arg0: RekapFilter): Promise<Array<RekapPeserta>> {
        if (this.processError) {
            try {
                const result = await this.actor.rekapPerPeserta(to_candid_RekapFilter_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rekapPerPeserta(to_candid_RekapFilter_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async ringkasanSesi(arg0: SesiId): Promise<RingkasanStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.ringkasanSesi(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ringkasanSesi(arg0);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async setAmbang(arg0: AmbangInput): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.setAmbang(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAmbang(arg0);
            return result;
        }
    }
    async simpanAbsensi(arg0: SimpanAbsensiInput): Promise<RingkasanStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.simpanAbsensi(to_candid_SimpanAbsensiInput_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.simpanAbsensi(to_candid_SimpanAbsensiInput_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async tambahMapel(arg0: MataPelajaranInput): Promise<MataPelajaran> {
        if (this.processError) {
            try {
                const result = await this.actor.tambahMapel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.tambahMapel(arg0);
            return result;
        }
    }
    async tambahPeserta(arg0: PesertaInput): Promise<Peserta> {
        if (this.processError) {
            try {
                const result = await this.actor.tambahPeserta(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.tambahPeserta(arg0);
            return result;
        }
    }
    async ubahMapel(arg0: MapelId, arg1: MataPelajaranInput): Promise<MataPelajaran | null> {
        if (this.processError) {
            try {
                const result = await this.actor.ubahMapel(arg0, arg1);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ubahMapel(arg0, arg1);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async ubahPeserta(arg0: PesertaId, arg1: PesertaInput): Promise<Peserta | null> {
        if (this.processError) {
            try {
                const result = await this.actor.ubahPeserta(arg0, arg1);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ubahPeserta(arg0, arg1);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async ubahSesi(arg0: SesiId, arg1: SesiInput): Promise<Sesi | null> {
        if (this.processError) {
            try {
                const result = await this.actor.ubahSesi(arg0, to_candid_SesiInput_n6(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ubahSesi(arg0, to_candid_SesiInput_n6(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Absensi_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Absensi): Absensi {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_DashboardRingkasan_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardRingkasan): DashboardRingkasan {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_MediaSesi_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaSesi): MediaSesi {
    return "zoom" in value ? MediaSesi.zoom : "whatsapp" in value ? MediaSesi.whatsapp : "tatapMuka" in value ? MediaSesi.tatapMuka : value;
}
function from_candid_PesertaAbsensiView_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PesertaAbsensiView): PesertaAbsensiView {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_SesiDetail_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SesiDetail): SesiDetail {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_SesiRingkas_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SesiRingkas): SesiRingkas {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Sesi_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sesi): Sesi {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_StatusAbsensi_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StatusAbsensi): StatusAbsensi {
    return "hadir" in value ? StatusAbsensi.hadir : "alpa" in value ? StatusAbsensi.alpa : "izin" in value ? StatusAbsensi.izin : "sakit" in value ? StatusAbsensi.sakit : value;
}
function from_candid_UserRole_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RekapKelompok]): RekapKelompok | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SesiRingkas]): SesiRingkas | null {
    return value.length === 0 ? null : from_candid_SesiRingkas_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SesiDetail]): SesiDetail | null {
    return value.length === 0 ? null : from_candid_SesiDetail_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Peserta]): Peserta | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PesertaId]): PesertaId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Sesi]): Sesi | null {
    return value.length === 0 ? null : from_candid_Sesi_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MataPelajaran]): MataPelajaran | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SesiId;
    media: _MediaSesi;
    kelompokId: _KelompokId;
    pemateri: string;
    tanggal: _Timestamp;
    mapelId: _MapelId;
    jendelaSelesai: _Timestamp;
    checkInToken: [] | [string];
    jendelaMulai: _Timestamp;
    tempat: [] | [string];
}): {
    id: SesiId;
    media: MediaSesi;
    kelompokId: KelompokId;
    pemateri: string;
    tanggal: Timestamp;
    mapelId: MapelId;
    jendelaSelesai: Timestamp;
    checkInToken?: string;
    jendelaMulai: Timestamp;
    tempat?: string;
} {
    return {
        id: value.id,
        media: from_candid_MediaSesi_n11(_uploadFile, _downloadFile, value.media),
        kelompokId: value.kelompokId,
        pemateri: value.pemateri,
        tanggal: value.tanggal,
        mapelId: value.mapelId,
        jendelaSelesai: value.jendelaSelesai,
        checkInToken: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.checkInToken)),
        jendelaMulai: value.jendelaMulai,
        tempat: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.tempat))
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _StatusAbsensi;
    dicatatOleh: [] | [Principal];
    sesiId: _SesiId;
    waktuCatat: _Timestamp;
    pesertaId: _PesertaId;
    catatan: string;
}): {
    status: StatusAbsensi;
    dicatatOleh?: Principal;
    sesiId: SesiId;
    waktuCatat: Timestamp;
    pesertaId: PesertaId;
    catatan: string;
} {
    return {
        status: from_candid_StatusAbsensi_n15(_uploadFile, _downloadFile, value.status),
        dicatatOleh: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.dicatatOleh)),
        sesiId: value.sesiId,
        waktuCatat: value.waktuCatat,
        pesertaId: value.pesertaId,
        catatan: value.catatan
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    halaqahTerendah: [] | [_RekapKelompok];
    kehadiranBulanIni: number;
    sesiTerdekat: [] | [_SesiRingkas];
}): {
    halaqahTerendah?: RekapKelompok;
    kehadiranBulanIni: number;
    sesiTerdekat?: SesiRingkas;
} {
    return {
        halaqahTerendah: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.halaqahTerendah)),
        kehadiranBulanIni: value.kehadiranBulanIni,
        sesiTerdekat: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.sesiTerdekat))
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SesiId;
    media: _MediaSesi;
    kelompokId: _KelompokId;
    pemateri: string;
    tanggal: _Timestamp;
    mapelId: _MapelId;
}): {
    id: SesiId;
    media: MediaSesi;
    kelompokId: KelompokId;
    pemateri: string;
    tanggal: Timestamp;
    mapelId: MapelId;
} {
    return {
        id: value.id,
        media: from_candid_MediaSesi_n11(_uploadFile, _downloadFile, value.media),
        kelompokId: value.kelompokId,
        pemateri: value.pemateri,
        tanggal: value.tanggal,
        mapelId: value.mapelId
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    peserta: Array<_PesertaAbsensiView>;
    sesi: _Sesi;
}): {
    peserta: Array<PesertaAbsensiView>;
    sesi: Sesi;
} {
    return {
        peserta: from_candid_vec_n26(_uploadFile, _downloadFile, value.peserta),
        sesi: from_candid_Sesi_n9(_uploadFile, _downloadFile, value.sesi)
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _StatusAbsensi;
    nama: string;
    pesertaId: _PesertaId;
    catatan: string;
}): {
    status: StatusAbsensi;
    nama: string;
    pesertaId: PesertaId;
    catatan: string;
} {
    return {
        status: from_candid_StatusAbsensi_n15(_uploadFile, _downloadFile, value.status),
        nama: value.nama,
        pesertaId: value.pesertaId,
        catatan: value.catatan
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n34(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n38(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PesertaAbsensiView>): Array<PesertaAbsensiView> {
    return value.map((x)=>from_candid_PesertaAbsensiView_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Sesi>): Array<Sesi> {
    return value.map((x)=>from_candid_Sesi_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Absensi>): Array<Absensi> {
    return value.map((x)=>from_candid_Absensi_n13(_uploadFile, _downloadFile, x));
}
function to_candid_AbsensiInput_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AbsensiInput): _AbsensiInput {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid_MediaSesi_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaSesi): _MediaSesi {
    return value == MediaSesi.zoom ? {
        zoom: null
    } : value == MediaSesi.whatsapp ? {
        whatsapp: null
    } : value == MediaSesi.tatapMuka ? {
        tatapMuka: null
    } : value;
}
function to_candid_PesertaFilter_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PesertaFilter): _PesertaFilter {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_RekapFilter_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RekapFilter): _RekapFilter {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_SesiFilter_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SesiFilter): _SesiFilter {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_SesiInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SesiInput): _SesiInput {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_SimpanAbsensiInput_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SimpanAbsensiInput): _SimpanAbsensiInput {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_StatusAbsensi_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StatusAbsensi): _StatusAbsensi {
    return value == StatusAbsensi.hadir ? {
        hadir: null
    } : value == StatusAbsensi.alpa ? {
        alpa: null
    } : value == StatusAbsensi.izin ? {
        izin: null
    } : value == StatusAbsensi.sakit ? {
        sakit: null
    } : value;
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tahun?: bigint;
    kelompokId?: KelompokId;
    bulan?: bigint;
}): {
    tahun: [] | [bigint];
    kelompokId: [] | [_KelompokId];
    bulan: [] | [bigint];
} {
    return {
        tahun: value.tahun ? candid_some(value.tahun) : candid_none(),
        kelompokId: value.kelompokId ? candid_some(value.kelompokId) : candid_none(),
        bulan: value.bulan ? candid_some(value.bulan) : candid_none()
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kelompokId?: KelompokId;
    nama?: string;
}): {
    kelompokId: [] | [_KelompokId];
    nama: [] | [string];
} {
    return {
        kelompokId: value.kelompokId ? candid_some(value.kelompokId) : candid_none(),
        nama: value.nama ? candid_some(value.nama) : candid_none()
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tahun?: bigint;
    kelompokId?: KelompokId;
    mapelId?: MapelId;
    bulan?: bigint;
}): {
    tahun: [] | [bigint];
    kelompokId: [] | [_KelompokId];
    mapelId: [] | [_MapelId];
    bulan: [] | [bigint];
} {
    return {
        tahun: value.tahun ? candid_some(value.tahun) : candid_none(),
        kelompokId: value.kelompokId ? candid_some(value.kelompokId) : candid_none(),
        mapelId: value.mapelId ? candid_some(value.mapelId) : candid_none(),
        bulan: value.bulan ? candid_some(value.bulan) : candid_none()
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    daftar: Array<AbsensiInput>;
    sesiId: SesiId;
}): {
    daftar: Array<_AbsensiInput>;
    sesiId: _SesiId;
} {
    return {
        daftar: to_candid_vec_n51(_uploadFile, _downloadFile, value.daftar),
        sesiId: value.sesiId
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: StatusAbsensi;
    pesertaId: PesertaId;
    catatan: string;
}): {
    status: _StatusAbsensi;
    pesertaId: _PesertaId;
    catatan: string;
} {
    return {
        status: to_candid_StatusAbsensi_n54(_uploadFile, _downloadFile, value.status),
        pesertaId: value.pesertaId,
        catatan: value.catatan
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    media: MediaSesi;
    kelompokId: KelompokId;
    pemateri: string;
    tanggal: Timestamp;
    mapelId: MapelId;
    jendelaSelesai: Timestamp;
    jendelaMulai: Timestamp;
    tempat?: string;
}): {
    media: _MediaSesi;
    kelompokId: _KelompokId;
    pemateri: string;
    tanggal: _Timestamp;
    mapelId: _MapelId;
    jendelaSelesai: _Timestamp;
    jendelaMulai: _Timestamp;
    tempat: [] | [string];
} {
    return {
        media: to_candid_MediaSesi_n8(_uploadFile, _downloadFile, value.media),
        kelompokId: value.kelompokId,
        pemateri: value.pemateri,
        tanggal: value.tanggal,
        mapelId: value.mapelId,
        jendelaSelesai: value.jendelaSelesai,
        jendelaMulai: value.jendelaMulai,
        tempat: value.tempat ? candid_some(value.tempat) : candid_none()
    };
}
function to_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<AbsensiInput>): Array<_AbsensiInput> {
    return value.map((x)=>to_candid_AbsensiInput_n52(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
